baseURL = 'https://artinessa.me/'

languageCode = 'ru-RU'
defaultContentLanguage = "ru"
defaultContentLang = "ru"

summaryLength = 30

[[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Статьи"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Обо мне"
  url = "/about"
  weight = 4
